"""empty message

Revision ID: 1bfef02298bb
Revises: b4b708a04f65
Create Date: 2024-12-03 13:31:44.498611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bfef02298bb'
down_revision = 'b4b708a04f65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('driver', sa.Text(), nullable=False),
    sa.Column('day_depature', sa.Text(), nullable=False),
    sa.Column('day_return', sa.Text(), nullable=False),
    sa.Column('date_depature', sa.DateTime(), nullable=True),
    sa.Column('date_return', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trips')
    # ### end Alembic commands ###
