"""empty message

Revision ID: fb43a3f328fd
Revises: 1bfef02298bb
Create Date: 2024-12-03 15:32:35.730753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb43a3f328fd'
down_revision = '1bfef02298bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('date_depature')
        batch_op.drop_column('date_return')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_return', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('date_depature', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
